spring:
  application:
    name: gen-ai-service
  config:
    import: "optional:configserver:${CONFIG_SERVER_URL:http://config-server:8888/}"
  ai:
    openai:
      api-key: ${API_KEY}
      base-url: https://generativelanguage.googleapis.com/v1beta/openai/
      chat:
        options:
          model: models/gemini-2.5-flash

server:
  port: ${PORT:8084}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://discovery-server:8761/eureka/}


